### ISSUE TITLE
Research on how to make theme on Jekyll

### ISSUE THREAD

**Issue by hyecheol123** [hyecheol123/KSEAWebDocuments#14]

**Comment by hyecheol123** [comment]
Need to summarize information and important steps in the [link 1](http://paikwiki.github.io/2018/10/create-your-own-jekyll-theme-gem-ko), [Link 2](https://ryandevelops.com/collection/2018-10-07-create-your-own-jekyll-theme-gem), and find more relevent data about the way to generate the theme. If we have to know some knowledge of Ruby, it is requested to place here.

**Comment by hyecheol123** [comment]
Markdown Files must be created, and needs to be written not only containing the information indicated, but also the related information. Think aboug how we can use this functions to make our website

**Comment by Drag-yong** [comment]
Finished
